name: Typesense Docsearch Action

on: 
  schedule:
    - cron: "0 2 15 * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run DocSearch Scraper
        uses: celsiusnarhwal/typesense-scraper@v2
        with:
          api-key: ${{ secrets.TYPESENSE_ADMIN_API_KEY }}
          host: sc4dhrl167jef08yp-1.a1.typesense.net
          port: 443
          protocol: https
          config: docsearch.json
